### ISSUE TITLE
Utility Curve not changing

### ISSUE THREAD

**Issue by MihailTrajkovski** [SirPolly/UtilityAI#4]
Hey, 

I wrote to you once before and finally I get my chance to include it in my project and I have a bug. Since the project is already more than a year in production I use Unity 2017 and I've read that you haven't test it on older version so I wouldn't be mad if you close the issue outright, but whenever I try to change the Utility Curve(the animation curve), I can succesfully change it in the window but the contextual scorer node animation curve doesn't change no matter what I try. Now I don't really have any big experience with editor scripts(and certainly not with more complex ones) so I wanted to ask you, approximately what could the issue be? So at least I can try and fix it myself.

**Comment by MihailTrajkovski** [comment]
A workaround I found just now is to simply click save and edit the scriptable object that's part of the brain and it updates the data on the editor node too. Don't know if this was always the intended way, so I don't know if I should close the issue.

**Comment by OneManMonkeySquad** [comment]
Heyho,

I tried it with 2017.4.26f1 and could reproduce the issue once. I think that's caused by the ScriptableObject not being instantly persisted to the asset file. Not sure. I pushed some changes, see if that fixes it for you.

Directly editing the asset is a valid workaround for any bugs in the editor, yes. But no, it's not the intended workflow.

**Comment by MihailTrajkovski** [comment]
Hey,

Great that you took the time to look into this issue. Sadly no this didn't fix the issue, but it might be on my side too since I am using 2017.1(don't really want to update especially since the game release is nearby). Anyways it's more important to me that is functional. One other issue I encountered was that I can't delete nodes(it's something I can ignore really), hopefully I won't come across any behavioral bugs that I can't fix, otherwise this is a pretty good package! And from what I've seen I like it more than Apex Utility. Thank you for looking into this issue and if you don't have an idea how to fix the deleting issue you can close this issue.

**Comment by OneManMonkeySquad** [comment]
Thanks for these kind words. I'll add node deletion some time in the future (soon™).
